general:
  log_level: "debug"
application:
  port: 8000
  hmac_secret: "qwR5th-4JkaqW-7iL2e-bNpEf-tY7ikDs-g3tuyui-wRgh6-ssddswFG-G6iH12W-ghJsq"
  redis_uri: "redis://127.0.0.1:6379"
database: 
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000